language: python
sudo: false
python:
    - 2.7
    - 3.6
env:
    - EXTRA=
matrix:
    include:
        - python: 2.7
          env: EXTRA=-zserver
    allow_failures:
    - python: 3.6
install:
    - pip install six==1.10.0 # force to avoid conflict with zc.recipe.testrunner
    - pip install -U setuptools==33.1.1
    - pip install zc.buildout coverage coveralls
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test$EXTRA --all -cv
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
    - develop/
